1. What is a Decision Tree, and how does it work	

ans.A decision tree is a flowchart-like structure used for decision-making and problem-solving, particularly in fields like data analysis and machine learning. It visually represents potential decisions, consequences, and outcomes, helping to identify the most favorable course of action. 

2.What are impurity measures in Decision Trees.

ans.mpurity measures in decision trees quantify the "messiness" or "heterogeneity" of classes within a node. They help determine how well a split divides the data into more homogeneous groups, which is crucial for building an effective predictive model. Commonly used impurity measures include Gini impurity and entrop

3. What is the mathematical formula for Gini Impurity	

https://www.google.com/imgres?q=what%20is%20mathematical%20formula%20for%20gini%20entropy&imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A610%2F1*Ag2dXbJt-1M9_S_bi8UBSw.png&imgrefurl=https%3A%2F%2Fmedium.com%2F%40arpita.k20%2Fgini-impurity-and-entropy-for-decision-tree-68eb139274d1&docid=wuXWOhIAgeeGOM&tbnid=ajg4rL1qPm_QkM&vet=12ahUKEwiI7_fz39KMAxWgk1YBHV7yCMgQM3oECBYQAA..i&w=305&h=152&hcb=2&ved=2ahUKEwiI7_fz39KMAxWgk1YBHV7yCMgQM3oECBYQAA

4.What is the mathematical formula for Entropy	

https://www.google.com/imgres?q=%22*%20What%20is%20the%20mathematical%20formula%20for%20Entropy%20in%20ml&imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A920%2F1*Aza8W1mxumLBgkU7OYh_tg.jpeg&imgrefurl=https%3A%2F%2Fthisgoke.medium.com%2Fentropy-a-method-for-data-science-machine-learning-7c3de2c6d82d&docid=NbFK-oYte3GDFM&tbnid=Vd3vfDuSfiP-EM&vet=12ahUKEwjy76744dKMAxU-4jgGHcVVLu0QM3oECBsQAA..i&w=460&h=120&hcb=2&ved=2ahUKEwjy76744dKMAxU-4jgGHcVVLu0QM3oECBsQAA

5. What is Information Gain, and how is it used in Decision Trees	

ans.nformation Gain, in the context of decision trees, is a measure that quantifies how much the uncertainty or entropy of a dataset is reduced when a specific feature is used to split it

which feature is root node is decided by information gain, the feature after splitting getting higher information gian is used as a root node in decision tree. 

6.,* What is the mathematical explanation behind Decision Trees	


ans.Decision trees use mathematical concepts like entropy, Gini impurity, and information gain to guide the splitting of data at each node. These metrics quantify the "impurity" or randomness within a set of data, and the algorithm aims to choose splits that maximize information gain, meaning they reduce the impurity as much as possibl

7.What is Pre-Pruning in Decision Trees	


Pre-pruning in decision trees, also known as early stopping, is a technique that limits the growth of a decision tree before it fully develops. It prevents overfitting by halting the tree-building process based on predefined criteria, such as maximum tree depth or minimum impurity decrease.

8. What is Post-Pruning in Decision Trees	

ans.Post-pruning in decision trees is a technique where the decision tree is allowed to grow fully, potentially overfitting the training data, and then branches are removed to improve generalization performance on unseen data

9 What is the difference between Pre-Pruning and Post-Pruning	

ans.Pre-pruning and post-pruning are two methods for preventing overfitting in decision trees. Pre-pruning involves stopping the tree's growth before it reaches its maximum depth or size, while post-pruning allows the tree to grow fully and then removes branches that are not providing significant value

10.* What is a Decision Tree Regressor	

ans.A decision tree regressor is a supervised machine learning algorithm that uses a tree-like model to predict continuous numerical values by recursively splitting data based on features to minimize prediction errors, ultimately leading to leaf nodes that represent the predicted values. 

11.'* What are the advantages and disadvantages of Decision Trees	

ans.Decision trees offer advantages like interpretability and the ability to handle various data types, while also having disadvantages such as overfitting and instability. They are relatively easy to understand and visualize

12.* How does a Decision Tree handle missing values	

ans.The algorithm calculates impurity measures (like Gini impurity or entropy) while considering the weights of individual instances. This means instances with missing values are not excluded but are given less weight in the impurity calculation, effectively reducing their influence on the split decision

12.how does a Decision Tree handle categorical features	

Decision trees naturally handle categorical features by creating separate branches or splits in the tree for each distinct value within a categorical feature. This allows the tree to effectively partition the data based on the different categories, leading to more accurate predictions

13.What are some real-world applications of Decision Trees?

ans.Decision trees find applications in various fields like finance, healthcare, and marketing, aiding in tasks such as predicting customer behavior, risk assessment, and decision-making. They are also used in machine learning for classification and regression

In [1]:
#practical
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

16.Write a Python program to train a Decision Tree Classifier on the Iris dataset and print the model accuracy*

In [2]:
df=sns.load_dataset("tips")

In [3]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [4]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [5]:
from sklearn.tree import DecisionTreeRegressor

In [6]:
df["sex"]=df["sex"].map({"Female":1,"Male":0})
df["smoker"]=df["smoker"].map({"Yes":1,"No":0})     #eda to clean the data
df["time"]=df["time"].map({"Dinner":1,"Lunch":0})
df["day"]=df["day"].map({"Sun":1,"Fri":2,"Sat":3,"Thur":4})

In [7]:
df["day"].unique()

[1, 3, 4, 2]
Categories (4, int64): [4, 2, 3, 1]

In [8]:
df

total_bill   tip sex smoker day time  size
0         16.99  1.01   1      0   1    1     2
1         10.34  1.66   0      0   1    1     3
2         21.01  3.50   0      0   1    1     3
3         23.68  3.31   0      0   1    1     2
4         24.59  3.61   1      0   1    1     4
..          ...   ...  ..    ...  ..  ...   ...
239       29.03  5.92   0      0   3    1     3
240       27.18  2.00   1      1   3    1     2
241       22.67  2.00   0      1   3    1     2
242       17.82  1.75   0      0   3    1     2
243       18.78  3.00   1      0   4    1     2

[244 rows x 7 columns]

In [9]:
from sklearn.model_selection import train_test_split
x=df.drop("total_bill",axis=1)
y=df["total_bill"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [10]:
clf=DecisionTreeRegressor()

In [11]:
clf.fit(x_train,y_train)

DecisionTreeRegressor()

In [12]:
y_pred=clf.predict(x_test)

In [13]:
from sklearn.metrics import r2_score,accuracy_score

In [14]:
r2_score(y_test,y_pred)

0.1914472530762361

17. Write a Python program to train a Decision Tree Classifier using Gini Impurity as the criterion and print the
feature importances*

In [34]:
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [35]:
clf=DecisionTreeClassifier(criterion="gini")

In [36]:
clf

DecisionTreeClassifier()

In [ ]:
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn import tree
plt.figure(figsize=(12,10))
tree.plot_tree(clf,filled=True)
plt.show()

 18.Write a Python program to train a Decision Tree Classifier using Entropy as the splitting criterion and print the
model accuracy*

In [ ]:
x,y=make_classification(n_samples=1000,n_features=5,n_classes=2)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(criterion="entropy")

In [ ]:
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_pred,y_test)

In [ ]:
from sklearn import tree
plt.figure(figsize=(12,10))
tree.plot_tree(clf,filled=True)
plt.show()

19. Write a Python program to train a Decision Tree Regressor on a housing dataset and evaluate using Mean
Squared Error (MSE)

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
data=fetch_california_housing()

In [ ]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [ ]:
df["price"]=data.target

In [ ]:
df

In [ ]:
#predict price of house based on following features

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
clf=DecisionTreeRegressor(criterion="squared_error")

In [ ]:
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

20. Write a Python program to train a Decision Tree Classifier and visualize the tree using graphviz

In [ ]:
x,y=make_classification(n_samples=100,n_features=3,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn import tree
plt.figure(figsize=(12,10))
tree.plot_tree(clf,filled=True)
plt.show()
x[1]

21.Write a Python program to train a Decision Tree Classifier with a maximum depth of 3 and compare its
accuracy with a fully grown tree.

In [ ]:
#case 1 fully grown tree
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
#case 1 fully grown tree max depth=3
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier(max_depth=3)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
#accuracy little decrease

22.Write a Python program to train a Decision Tree Classifier using min_samples_split=5 and compare its
accuracy with a default tree.

In [ ]:
#case 1 fully grown tree
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
accuracy_score(y_test,y_pred)

In [ ]:
#case 1 fully grown tree max depth=3
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier(min_samples_split=3)
clf.fit(x_train,y_train)
y_pred1=clf.predict(x_test)
accuracy_score(y_test,y_pred1)

23.Write a Python program to apply feature scaling before training a Decision Tree Classifier and compare its
accuracy with unscaled data.

In [ ]:
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=2)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
from sklearn.preprocessing import StandardScaler
scal=StandardScaler()
x_train=scal.fit_transform(x_train)
x_test=scal.transform(x_test)
clf_scal=DecisionTreeClassifier()
clf_scal.fit(x_train,y_train)
y_pred_2=clf_scal.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred_2)

 24.Write a Python program to train a Decision Tree Classifier using One-vs-Rest (OvR) strategy for multiclass
classification*

In [ ]:
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=3)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

25. Write a Python program to train a Decision Tree Classifier and display the feature importance scores

In [ ]:
x,y=make_classification(n_samples=1000,n_features=5,n_informative=3,n_redundant=0,n_classes=3)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

26.Train a Gradient Boosting Classifier and visualize the ROC curve.

In [31]:
#gradient classfier

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


import warnings
warnings.filterwarnings('ignore')

In [20]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=1)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [22]:
clf = GradientBoostingClassifier()
clf

GradientBoostingClassifier()

In [23]:
clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [24]:
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

In [25]:
# Evaluate the model
print("Current model performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Current model performance:
Accuracy: 0.8633333333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.88      0.86       139
           1       0.89      0.84      0.87       161

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.87      0.86      0.86       300

Confusion Matrix:
[[123  16]
 [ 25 136]]


27.Train an XGBoost Regressor and tune the learning rate using GridSearchCV.

In [28]:
#hyperpraremeter tuning
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.05, 0.2]}

In [29]:
param_grid

{'n_estimators': [100, 200, 300], 'learning_rate': [0.01, 0.1, 0.05, 0.2]}

In [32]:
gbc = GradientBoostingClassifier()
grid_search = GridSearchCV(estimator = gbc, param_grid=param_grid, cv = 5, verbose=3)
grid_search

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [33]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.01, n_estimators=100;, score=0.857 total time=   2.6s
[CV 2/5] END learning_rate=0.01, n_estimators=100;, score=0.907 total time=   2.3s
[CV 3/5] END learning_rate=0.01, n_estimators=100;, score=0.857 total time=   2.2s
[CV 4/5] END learning_rate=0.01, n_estimators=100;, score=0.850 total time=   2.1s
[CV 5/5] END learning_rate=0.01, n_estimators=100;, score=0.821 total time=   2.3s
[CV 1/5] END learning_rate=0.01, n_estimators=200;, score=0.857 total time=   4.4s
[CV 2/5] END learning_rate=0.01, n_estimators=200;, score=0.893 total time=   4.3s
[CV 3/5] END learning_rate=0.01, n_estimators=200;, score=0.864 total time=   4.3s
[CV 4/5] END learning_rate=0.01, n_estimators=200;, score=0.836 total time=   4.2s
[CV 5/5] END learning_rate=0.01, n_estimators=200;, score=0.829 total time=   4.2s
[CV 1/5] END learning_rate=0.01, n_estimators=300;, score=0.850 total time=   6.6s
[CV 2/5] END learning_rate

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [37]:
best_model = grid_search.best_estimator_
y_pred_tuned = best_model.predict(X_test)

# Evaluate the tuned model
print("Tuned model performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_tuned)}")
print("Classification Report:")
print(classification_report(y_test, y_pred_tuned))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_tuned))

Tuned model performance:
Accuracy: 0.48333333333333334
Classification Report:
              precision    recall  f1-score   support

           0       0.49      0.48      0.49       153
           1       0.47      0.49      0.48       147

    accuracy                           0.48       300
   macro avg       0.48      0.48      0.48       300
weighted avg       0.48      0.48      0.48       300

Confusion Matrix:
[[73 80]
 [75 72]]


29. Train an AdaBoost Classifier and analyze the effect of different learning rates.

In [38]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=1)

In [42]:
#adboost classfier

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [44]:
classifier = AdaBoostClassifier()
classifier

AdaBoostClassifier()

In [45]:
classifier.fit(X_train, y_train)

AdaBoostClassifier()

In [46]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

In [47]:
# Evaluate the model
print("Current model performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Current model performance:
Accuracy: 0.8333333333333334
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       139
           1       0.86      0.83      0.84       161

    accuracy                           0.83       300
   macro avg       0.83      0.83      0.83       300
weighted avg       0.83      0.83      0.83       300

Confusion Matrix:
[[117  22]
 [ 28 133]]


4 Train an XGBoost Classifier for multi-class classification and evaluate using log-loss.

In [ ]:
from sklearn.preprocessing import StandardScaler
scal=StandardScaler()
x_train=scal.fit_transform(x_train)
x_test=scal.transform(x_test)
clf_scal=DecisionTreeClassifier()
clf_scal.fit(x_train,y_train)
y_pred_2=clf_scal.predict(x_test)