In [22]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

arr=np.random.randint(1,100,(3,3))
print(arr)
print(arr.T)

#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

lis=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(lis)
arr1

arr1.reshape(2,5)
arr1.reshape(5,2)

#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
np.abs(np.random.randn(4,4))
np.pad(np.abs(np.random.randn(4,4)),1)

#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

arr=np.arange(10,60,5)
print(arr)

#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.

arr=np.array(['python', 'numpy', 'pandas'])
print(arr)
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

arr=np.array(['python', 'numpy', 'pandas'])
print(arr)
print(np.char.join(' ',arr))

#7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2

#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

arr=np.eye(5)
arr
np.diag(arr)

#9.9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array

arr=np.random.randint(0,1000,100)
print(arr)
for i in arr:
  if i%2!=0:
    print(i)

#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.

temp=np.linspace(25,30,30)
temp
temp[0:8]


[[93 43 22]
 [44 96 28]
 [62 46  7]]
[[93 44 62]
 [43 96 46]
 [22 28  7]]
[10 15 20 25 30 35 40 45 50 55]
['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['python' 'numpy' 'pandas']
['p y t h o n' 'n u m p y' 'p a n d a s']
[972 380 645 432 498 801 329 370 576 210  65 808 180 151 201 710 609  86
 236 336   3 785 518 152 800 733 510 870 164 500 213 663 800  66 234  33
 690 562 961 615 412 862 991 779 286 877 338 907 727 291 202 774 510 162
 958 341 344 612 862 835 766 661 371 114 656 949 488 492 942 849  73 624
 743  22  99 477 989 953 815  28 252 131 645 628 505 669 698 496 859 133
 956 932 944 849 116 206 144 234 943 807]
645
801
329
65
151
201
609
3
785
733
213
663
33
961
615
991
779
877
907
727
291
341
835
661
371
949
849
73
743
99
477
989
953
815
131
645
505
669
859
133
849
943
807


array([25.        , 25.17241379, 25.34482759, 25.51724138, 25.68965517,
       25.86206897, 26.03448276, 26.20689655])